# Generated by Django 2.1.5 on 2021-07-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_feedback_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='BMI',
            field=models.FloatField(),
        ),
    ]
