# Generated by Django 2.1.5 on 2021-07-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210715_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='DiabetesPedigreeFunction',
            field=models.FloatField(),
        ),
    ]
